"""added join relationship between messages and users

Revision ID: 03f838ca8ba3
Revises: 7b06b0d2ca39
Create Date: 2021-11-23 08:19:22.565716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03f838ca8ba3'
down_revision = '7b06b0d2ca39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_sender_id_fkey', 'messages', type_='foreignkey')
    op.drop_column('messages', 'sender_id')
    op.add_column('user_messages', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_messages', type_='foreignkey')
    op.drop_column('user_messages', 'sender_id')
    op.add_column('messages', sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('messages_sender_id_fkey', 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
