"""empty message
Upgraded user model to include avatar, and timestamps
Revision ID: 5e2b3555e22e
Revises: ffdc0a98111c
Create Date: 2021-11-16 16:08:58.040301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2b3555e22e'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'avatar', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column(
        'created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column(
        'updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
