"""specified foreignkeys in user_messages at string and list

Revision ID: 9427f8952f20
Revises: 03f838ca8ba3
Create Date: 2021-11-23 08:37:25.896132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9427f8952f20'
down_revision = '03f838ca8ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_messages', sa.Column('recipient_ids', sa.Integer(), nullable=True))
    op.drop_constraint('user_messages_recipient_id_fkey', 'user_messages', type_='foreignkey')
    op.create_foreign_key(None, 'user_messages', 'users', ['recipient_ids'], ['id'], ondelete='CASCADE')
    op.drop_column('user_messages', 'recipient_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_messages', sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_messages', type_='foreignkey')
    op.create_foreign_key('user_messages_recipient_id_fkey', 'user_messages', 'users', ['recipient_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_messages', 'recipient_ids')
    # ### end Alembic commands ###
