"""added channel_messages table and restructured relationships

Revision ID: 4f4f6e89cfce
Revises: 78656378457d
Create Date: 2022-01-05 16:55:05.843047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4f6e89cfce'
down_revision = '78656378457d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_messages',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id', 'sender_id', 'message_id')
    )
    op.drop_constraint('messages_channel_id_fkey', 'messages', type_='foreignkey')
    op.drop_column('messages', 'channel_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('messages_channel_id_fkey', 'messages', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.drop_table('channel_messages')
    # ### end Alembic commands ###
