"""recipient_ids is now recipient_id, renamed for clarity

Revision ID: 7dc90bc9da94
Revises: 4f4f6e89cfce
Create Date: 2022-01-23 16:00:07.290596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc90bc9da94'
down_revision = '4f4f6e89cfce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('user_chats', sa.Column('recipient_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_chats_recipient_ids_fkey', 'user_chats', type_='foreignkey')
    op.create_foreign_key(None, 'user_chats', 'users', ['recipient_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_chats', 'recipient_ids')
    op.add_column('user_messages', sa.Column('recipient_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_messages_recipient_ids_fkey', 'user_messages', type_='foreignkey')
    op.create_foreign_key(None, 'user_messages', 'users', ['recipient_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_messages', 'recipient_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_messages', sa.Column('recipient_ids', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_messages', type_='foreignkey')
    op.create_foreign_key('user_messages_recipient_ids_fkey', 'user_messages', 'users', ['recipient_ids'], ['id'], ondelete='CASCADE')
    op.drop_column('user_messages', 'recipient_id')
    op.add_column('user_chats', sa.Column('recipient_ids', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_chats', type_='foreignkey')
    op.create_foreign_key('user_chats_recipient_ids_fkey', 'user_chats', 'users', ['recipient_ids'], ['id'], ondelete='CASCADE')
    op.drop_column('user_chats', 'recipient_id')
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
