"""removed user_chat model and queries

Revision ID: 2911c32722ec
Revises: 963d43c5ed31
Create Date: 2022-01-24 13:59:43.574484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2911c32722ec'
down_revision = '963d43c5ed31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_chats')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_chats',
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name='user_chats_chat_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name='user_chats_recipient_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='user_chats_sender_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', name='user_chats_pkey')
    )
    # ### end Alembic commands ###
